version: '3.7'
services: 
  apiGateway:
    image: malejandro13/nginx-php73-dev:latest
    container_name: apiGateway
    volumes:
      - ./ApiGateway:/var/www/html
    ports:
      - 8000:80
  authorApi:
    image: malejandro13/nginx-php73-dev:latest
    container_name: authorApi
    volumes:
      - ./AuthorApi:/var/www/html
    ports:
      - 8001:80
  bookApi:
    image: malejandro13/nginx-php73-dev:latest
    container_name: bookApi
    volumes:
      - ./BookApi:/var/www/html
    ports:
      - 8002:80